enableScripts: true

ignoredBuiltDependencies:
  - '@prisma/engines'
  - bcrypt
  - esbuild
  - prisma
  - sharp
  - unrs-resolver

onlyBuiltDependencies:
  - '@prisma/client'
  - core-js
  - lefthook
